// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjawcckldorumxzgdbyg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqYXdjY2tsZG9ydW14emdkYnlnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTg0NzAsImV4cCI6MjA2NzQzNDQ3MH0.RNFIaUPrRN4AiN1Dy2-iCQ5N0KgoQ0oJwF96P8mFgVY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});